name: app
description: HI

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.7
  bloc: ^8.1.0
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^13.0.0
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_native_splash: ^2.2.16
  go_router: ^6.0.1
  dartz: ^0.10.1
  f_logs: ^2.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  mockito: ^5.3.2
  http_mock_adapter: ^0.3.3
  integration_test: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/animation/
    - assets/jpg/


flutter_intl:
  enabled: true
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
